AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool for TaskMaster Authentication - FREE tier eligible'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # User Pool - FREE (50,000 MAUs)
  TaskMasterUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-taskmaster-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: company_id
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        Environment: !Ref Environment
        Service: TaskMaster

  # User Pool Client - FREE
  TaskMasterUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${Environment}-taskmaster-client'
      UserPoolId: !Ref TaskMasterUserPool
      GenerateSecret: false  # For web apps
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      CallbackURLs:
        - http://localhost:8000
        - http://localhost:3000
      LogoutURLs:
        - http://localhost:8000
        - http://localhost:3000
      SupportedIdentityProviders:
        - COGNITO

  # Identity Pool - FREE
  TaskMasterIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${Environment}_taskmaster_identity'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref TaskMasterUserPoolClient
          ProviderName: !GetAtt TaskMasterUserPool.ProviderName

  # IAM Role for authenticated users
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-cognito-authenticated-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref TaskMasterIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-projects'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-tasks'

  # Attach roles to identity pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref TaskMasterIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref TaskMasterUserPool
    Export:
      Name: !Sub '${Environment}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref TaskMasterUserPoolClient
    Export:
      Name: !Sub '${Environment}-UserPoolClientId'

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref TaskMasterIdentityPool
    Export:
      Name: !Sub '${Environment}-IdentityPoolId'

  AuthenticatedRoleArn:
    Description: IAM Role for authenticated users
    Value: !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${Environment}-AuthenticatedRoleArn'