AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for TaskMaster - FREE tier eligible'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # Projects Table
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-projects'
      BillingMode: PAY_PER_REQUEST  # FREE tier eligible
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: company_id
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: company-index
          KeySchema:
            - AttributeName: company_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: TaskMaster

  # Tasks Table
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-tasks'
      BillingMode: PAY_PER_REQUEST  # FREE tier eligible
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: assignee
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: project-index
          KeySchema:
            - AttributeName: project_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: assignee-index
          KeySchema:
            - AttributeName: assignee
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: TaskMaster

Outputs:
  ProjectsTableName:
    Description: Projects table name
    Value: !Ref ProjectsTable
    Export:
      Name: !Sub '${Environment}-ProjectsTable'

  TasksTableName:
    Description: Tasks table name
    Value: !Ref TasksTable
    Export:
      Name: !Sub '${Environment}-TasksTable'