name: 🚀 TaskMaster CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'app/backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: taskmaster-backend
  ECS_SERVICE: taskmaster-backend-dev
  ECS_CLUSTER: dev-cluster
  CODEBUILD_PROJECT: taskmaster-build

jobs:
  build-and-deploy:
    name: 🏗️ Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔐 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: 🏗️ Start CodeBuild
      run: |
        echo "🚀 Starting CodeBuild for TaskMaster..."
        BUILD_ID=$(aws codebuild start-build \
          --project-name ${{ env.CODEBUILD_PROJECT }} \
          --source-type-override NO_SOURCE \
          --buildspec-override file://buildspec-github.yml \
          --query 'build.id' --output text)
        
        echo "📋 Build ID: $BUILD_ID"
        echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
        
    - name: ⏳ Wait for CodeBuild completion
      run: |
        echo "⏳ Waiting for build $BUILD_ID to complete..."
        
        while true; do
          STATUS=$(aws codebuild batch-get-builds \
            --ids $BUILD_ID \
            --query 'builds[0].buildStatus' --output text)
          
          echo "📊 Build status: $STATUS"
          
          if [ "$STATUS" = "SUCCEEDED" ]; then
            echo "✅ Build completed successfully!"
            break
          elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "FAULT" ] || [ "$STATUS" = "STOPPED" ] || [ "$STATUS" = "TIMED_OUT" ]; then
            echo "❌ Build failed with status: $STATUS"
            exit 1
          fi
          
          sleep 30
        done
        
    - name: 🚀 Deploy to ECS
      run: |
        echo "🚀 Deploying to ECS..."
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --force-new-deployment \
          --query 'service.serviceName' --output text
          
        echo "✅ ECS deployment triggered!"
        
    - name: 🔍 Verify deployment
      run: |
        echo "🔍 Verifying deployment..."
        
        # Wait for service to stabilize
        aws ecs wait services-stable \
          --cluster ${{ env.ECS_CLUSTER }} \
          --services ${{ env.ECS_SERVICE }}
          
        # Get ALB DNS name
        ALB_DNS=$(aws cloudformation describe-stacks \
          --stack-name taskmaster-dev-alb \
          --query "Stacks[0].Outputs[?OutputKey=='ALBDNSName'].OutputValue" \
          --output text)
          
        echo "🌐 Application URL: http://$ALB_DNS"
        
        # Test health endpoint
        if curl -f "http://$ALB_DNS/health"; then
          echo "✅ Health check passed!"
        else
          echo "❌ Health check failed!"
          exit 1
        fi